### ISSUE TITLE
Forgetting to set the refinement in Obstacle

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#244]
### Expected behaviour
This was a a minor user error more than anything, but gave an error I'd not seen before, so thought I'd mention it.

When setting an upwards goal from within an Obstacle in one of its environments, I forgot to select 'obstruct' as a refinement, so once saved and updated in the sub-screen, it then shows as null in the listing (which is a normal cue to go back and add a refinement). As a side note, when you do the same process within a Goal, I think it displays and sets 'and' as a default, but there is no default in the Obstacle process (for which there may be a reason?).

### Actual behaviour
However, if I didn't spot the null and tried to save the Obstacle, nothing happens.
Actually, a quick check in the terminal shows me it gave an error. The error mentions a 'null' somewhere, so I instantly knew what I'd done and how to fix it - update the null to 'obstruct' and re-save.

### Steps to reproduce the behaviour
Steps are generally as noted as above. However, I mention the issue because to a new user it may not be obvious, despite it being a really minor issue... and because I haven't seen this error before.

For info, the terminal showed -

INFO:werkzeug:127.0.0.1 - - [03/May/2018 19:33:07] "PUT /api/obstacles/name/Found%20Lost%20FMC-TCCC?session_id=S0tb74ZitSx37omziRS8gIzjDIm0sQO7 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/ObstacleController.py", line 204, in put
    dao.update_obstacle(upd_obs, name)
  File "/home/cairisuser/cairis/cairis/data/ObstacleDAO.py", line 97, in update_obstacle
    self.db_proxy.updateObstacle(params)
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 2249, in updateObstacle
    self.addObstacleRefinements(obsId,obsName,environmentName,environmentProperties.goalRefinements(),environmentProperties.subGoalRefinements())
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 2059, in addObstacleRefinements
    self.addGoalAssociation(parameters)
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 1990, in addGoalAssociation
    self.updateDatabase('call addGoalAssociation(:assId,:env,:goal,:dim,:type,:sGName,:sGDName,:altId,:rationale)',{'assId':associationId,'env':envName,'goal':goalName,'dim':goalDimName,'type':aType,'sGName':subGoalName,'sGDName':subGoalDimName,'altId':alternativeId,'rationale':rationale},'MySQL error adding goal association')
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 255, in updateDatabase
    session.execute(callTxt,argDict)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1048, "Column 'ref_type_id' cannot be null") [SQL: u'call addGoalAssociation(%s,%s,%s,%s,%s,%s,%s,%s,%s)'] [parameters: (1298L, u'All Systems (Overview)', u'A - Provide SoS Mgmt and support functions for SoS Ops', u'goal', None, u'Found Lost FMC-TCCC', 'obstacle', 0, u'None')] (Background on this error at: http://sqlalche.me/e/e3q8)

### Version of CAIRIS
Current

### Operating Systems / Hardware 
As previous

**Comment by failys** [comment]
The javascript does set the default refinement type to 'obstruct' in such cases, but a typo in the obstacles HTML form meant this was ignored.  Should be fixed now.
