### ISSUE TITLE
Exporting to Trello - a new error

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#255]
### Expected behaviour
After adding a bunch more PersonaHelper captured doc refs (in MMN20180513), I've tried to Export to Trello again, just to see if it works yet. 

### Actual behaviour
It seems I've broken it a little more and it now creates an error in the terminal. I'm not quite sure what's happened, although strangely the board is created in Trello (as per Issue 252).

### Steps to reproduce the behaviour
I noticed when capturing things, if I have a factoid name with a hyphen (e.g. it's), it transferred into CAIRIS with slashes (e.g. Sometimes it\\\'s clear what injury takes priority). Unlike other slash issues I've had, I could easily access the doc ref info and update and remove the slashes. All seems fine there so shouldn't cause any issues with MMN20180513, and may not be related to this issue.

NOTE: The previous Trello issue submitted (252) didn't give and error in the terminal, although this issue is probably related in some way.

The new error shows -

INFO:werkzeug:127.0.0.1 - - [12/May/2018 21:35:48] "GET /api/document_references?session_id=test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/DocumentReferenceController.py", line 43, in get
    drs = dao.get_document_references(constraint_id=constraint_id)
  File "/home/cairisuser/cairis/cairis/data/DocumentReferenceDAO.py", line 42, in get_document_references
    drs = self.db_proxy.getDocumentReferences(constraint_id)
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 2638, in getDocumentReferences
    drRows = self.responseList('call getDocumentReferences(:id)',{'id':constraintId},'MySQL error getting document references')
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 337, in responseList
    rs = session.execute(callTxt,argDict)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1132, in _execute_context
    None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1125, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 427, in _revalidate_connection
    "Can't reconnect until invalid "
StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'call getDocumentReferences(%s)'] [parameters: [{'id': -1}]]

### Version of CAIRIS
Current

### Operating Systems / Hardware 
As previous

**Comment by failys** [comment]
I think this might be something which is fixed and/or uses reserved references.  If this problem hasn't been fixed, can you please try reproducing in an empty model, i.e. creating a single external document,  a document reference, and then exporting.

**Comment by D-Dev** [comment]
Ok no problem. I am currently working a a few more updates, and then I
shall re-test the process. Thanks as always!

**Comment by D-Dev** [comment]
Hi. Just to confirm, this error no longer exists. Thank you.
