### ISSUE TITLE
Unicode encoding problem 

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#303]
### Expected behaviour
As a result of copying from different sources, a different sized dash has been used. E.g In the Persona names:
Wanda Baker - On-site supervisor
Edwin Smith – CEO of emergency management non-profit

### Actual behaviour
The unicode conversion throws an error in some scenarios (e.g when in an asset name), or runs but doesn't display the details of the element.  It seems it's due to the longer dash character (u'\u2013')

### Steps to reproduce the behaviour
- e.g. see one of the personas Edwin in the last sent file (or the other personas with a long dash). When you access it, it doesn't display properly.

BUT...
Somewhere in between figuring this out and trying to fix the problems (e.g. in the xml), it had another weird moment that seems to have stopped so can't recreate. However, when clicking an asset (or few), it didn't display properly, then try again, then it had a funny moment, but then effectively results in an error that inserts a space (in the xml) and the end of the title, leaving a gap (character u'\xa0') before the quote mark. Oddly it tells you the error is because of the space - which it created. Bless it. Going back into the xml to take the space back out works around it, but it has stopped now.

INFO:werkzeug:127.0.0.1 - - [16/Sep/2018 08:43:31] "GET /api/assets/name/Public%20Safety%20Communications%C2%A0 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/AssetController.py", line 84, in get
    found_asset = dao.get_asset_by_name(name)
  File "/home/cairisuser/cairis/cairis/data/AssetDAO.py", line 87, in get_asset_by_name
    assetId = self.db_proxy.getDimensionId(name,'asset')
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 735, in getDimensionId
    dimensionName = self.conn.connection().connection.escape_string(dimensionName)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 28: ordinal not in range(128)

### Version of CAIRIS
Current

**Comment by failys** [comment]
Were you able to paste the long dash into the GUI when creating the persona?

**Comment by failys** [comment]
In any event, it sounds like this character should be added to the list here: https://cairis.readthedocs.io/en/latest/reserved.html

**Comment by D-Dev** [comment]
Yes, it pasted in fine, and saved fine. I didn't particularly need the long dash, so I should get into the habit of overwriting these things. It was only then when trying to do other things or link to other things the error becomes apparent (a bit like when I used to use & symbols - which seems to have be solved a while ago).

**Comment by failys** [comment]
Will close for now.  Updated documentation to indicate that non-ASCII characters should be avoided.
