### ISSUE TITLE
Use Case prevents export

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#304]
### Expected behaviour
After adding a couple of use cases, I tried export the xml file. (Failed)
I removed the use cases, and exported fine.

### Actual behaviour

No obvious issues in the use case, and it creates fine. But then won't export an xml file.

INFO:werkzeug:127.0.0.1 - - [16/Sep/2018 19:24:11] "GET /api/export/file?session_id=fCRxYb0c6IKTzimLVl9c4idiPTokbibT HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/CExportController.py", line 46, in get
    modelBuf = dao.file_export()
  File "/home/cairisuser/cairis/cairis/data/ExportDAO.py", line 39, in file_export
    xmlBuf+= self.db_proxy.synopsesToXml(0)[0] + '\n\n'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### Steps to reproduce the behaviour
Attached file used, but with use cases removed.

[MAA20180917.zip](https://github.com/failys/cairis/files/2387279/MAA20180917.zip)

### Version of CAIRIS
Current

**Comment by failys** [comment]
I've imported this model and created a use case, but can't reproduce this problem (i.e. I can export a model without any problem).  Can you please provide more detail about the use case you tried creating.

**Comment by D-Dev** [comment]
(Some Screenshot examples attached below) 
[ScreenShots.zip](https://github.com/failys/cairis/files/2388221/ScreenShots.zip)

Using the submitted file -
Create Use Case: App - Evacuee Alert
Code: App-EA
Author: D
Environment: Any (but use Mutual Aid for now)
Description: As a wildfire victim or someone affected by wildfire or disaster nearby, I need to be able to tell emergency personnel where I am and what I need so I can survive and-or escape.
Actor: The Evacuee
Pre-Con: A working device with power and signal to seek help.
Post-Con: A working device with power and signal to wait for updates and help.
Flow (just used one step for this example): 
   Step: Decision to contact help 
   Intentional Elements: Intention - Get help, Actor Type - Role, Actor - The Evacuee. (Note tried different combinations of assets or roles - e.g. do something, with asset, Emergency App)

Click Update - Updates fine
Then go to export model and I still get -

INFO:werkzeug:127.0.0.1 - - [17/Sep/2018 03:30:12] "GET /api/export/file?session_id=XsvbP0mjj2El6yJWnDAReW3XjpfH0ZKw HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/CExportController.py", line 46, in get
    modelBuf = dao.file_export()
  File "/home/cairisuser/cairis/cairis/data/ExportDAO.py", line 39, in file_export
    xmlBuf+= self.db_proxy.synopsesToXml(0)[0] + '\n\n'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by failys** [comment]
I've just pushed an update that fixes this.  It's a database update, so you'll need to re-run the quick setup script.  Can you please try pulling this update and seeing if the problem persists?

**Comment by D-Dev** [comment]
Yay - it exports. Thanks again!
