### ISSUE TITLE
Import Error (500)

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#418]
### Expected behaviour
Just done a fresh Git pull, quick setup (twice), and a UI install.

I'm now trying to import the current model. 

### Actual behaviour
This returns an error 500 shown in the browser.
Some data/models are imported. But, the goal model, for example is missing things, and only one use case was added to the db, so they don't show in models either. Can't tell how much the responsibility model is wrong...but have you updated the risk model, that looks different?
Dependencies, data flow and trust boundary data didn't get added to the db either.
The terminal returned the following errors:

ERROR:cairisd:[500] Unknown error: cannot unpack non-iterable IntegrityError object
ERROR:flask.app:Exception on /api/import/text [POST]
Traceback (most recent call last):
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 3491, in addTags
    curs.execute('call addTag(%s,%s,%s)',[dimObjt,tag,dimName])
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '1645-166' for key 'PRIMARY'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cairisuser/cairis/cairis/controllers/CImportController.py", line 102, in post
    result = dao.file_import(abs_path, type, overwrite)
  File "/home/cairisuser/cairis/cairis/data/ImportDAO.py", line 90, in file_import
    return file_import(importFile,mFormat,overwriteFlag,self.session_id)
  File "/home/cairisuser/cairis/cairis/bin/cimport.py", line 91, in file_import
    msgStr += importModelFile(importFile,int(overwriteFlag),session_id)
  File "/home/cairisuser/cairis/cairis/mio/ModelImport.py", line 808, in importModelFile
    modelTxt += importRequirementsFile(importFile,session_id) + ' '
  File "/home/cairisuser/cairis/cairis/mio/ModelImport.py", line 165, in importRequirementsFile
    return importRequirements(handler.domainProperties(),handler.goals(),handler.obstacles(),handler.requirements(),handler.usecases(),handler.countermeasures(),session_id = session_id)
  File "/home/cairisuser/cairis/cairis/mio/ModelImport.py", line 226, in importRequirements
    db_proxy.addUseCase(ucParameters)
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 3007, in addUseCase
    self.addTags(ucName,'usecase',tags)
  File "/home/cairisuser/cairis/cairis/core/MySQLDatabaseProxy.py", line 3495, in addTags
    id,msg = e
TypeError: cannot unpack non-iterable IntegrityError object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/CImportController.py", line 109, in post
    raise CairisHTTPError(status_code=500,message=str(ex),status='Unknown error')
cairis.daemon.CairisHTTPError.CairisHTTPError: 500 Internal Server Error: None
INFO:werkzeug:127.0.0.1 - - [27/Jul/2019 12:53:00] "POST /api/import/text HTTP/1.1" 500 -

[MAA-current.zip](https://github.com/failys/cairis/files/3438541/MAA-current.zip)

### Steps to reproduce the behaviour
Oh, and also tried this on demo.cairis

### Version of CAIRIS
Latest (today)

### Operating Systems / Hardware 
VMWare/Ub19.04

**Comment by failys** [comment]
Can you please pull the latest update, re-run the quick setup script, and try again.  cimport.py returns no errors for me after this update.

**Comment by failys** [comment]
Just pushed another update to the UI and server, so don't forget to run the installUI script too.  This update makes grouping of objects in risk models optional (click the tags checkbox if you want to turn this feature on).

**Comment by D-Dev** [comment]
It works, awesome, thanks :-)
