### ISSUE TITLE
Generating docs

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#419]
### Expected behaviour
Just as a quick test, I tried to generate some docs (from MAA-current.xml), just to see what happens

### Actual behaviour
...but they all came back with errors.
(Note: this is not stopping me working on something else...it's just FYI)

sh: 1: pandoc: not found
ERROR:cairisd:[500] Unknown error: report file not found
ERROR:flask.app:Exception on /api/documentation/type/Data Protection Impact Assessment/format/DOCX [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/DocumentationController.py", line 74, in get
    raise CairisHTTPError(status_code=500,message='report file not found',status='Unknown error')
cairis.daemon.CairisHTTPError.CairisHTTPError: 500 Internal Server Error: None
INFO:werkzeug:127.0.0.1 - - [27/Jul/2019 15:27:42] "GET /api/documentation/type/Data%20Protection%20Impact%20Assessment/format/DOCX?session_id=hOdAmk0D0XSmQ9XNDhF1ukBzqF0Aeqm8&filename=report HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [27/Jul/2019 15:29:22] "GET /api/documentation/type/Requirements/format/DOCX?session_id=hOdAmk0D0XSmQ9XNDhF1ukBzqF0Aeqm8&filename=report HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/DocumentationController.py", line 64, in get
    dao.generate_documentation(fileName,doc_type,sectionFlags,doc_format)
  File "/home/cairisuser/cairis/cairis/data/DocumentationDAO.py", line 35, in generate_documentation
    cairis.misc.DocumentBuilder.build(self.db_proxy,docType,sectionFlags,typeFlags,fileName,docDir)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 2309, in build
    specDoc = buildReqSpecBody(p,sectionFlags,docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 2167, in buildReqSpecBody
    specDoc += tasks(p,docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 800, in tasks
    chapterTxt += modelSection(p,'Task',docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 1285, in modelSection
    if (buildModel(p,environmentName,modelType,modelFile,'',fileSuffix) == True):
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 194, in buildModel
    drawGraph(model.graph(),'dot',graphFile,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/KaosModel.py", line 288, in graph
    self.buildNode(element[0],element[1])
  File "/home/cairisuser/cairis/cairis/misc/KaosModel.py", line 103, in buildNode
    if (currentScore > highestScore):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
INFO:werkzeug:127.0.0.1 - - [27/Jul/2019 15:30:10] "GET /api/documentation/type/Personas/format/DOCX?session_id=hOdAmk0D0XSmQ9XNDhF1ukBzqF0Aeqm8&filename=report HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/DocumentationController.py", line 64, in get
    dao.generate_documentation(fileName,doc_type,sectionFlags,doc_format)
  File "/home/cairisuser/cairis/cairis/data/DocumentationDAO.py", line 35, in generate_documentation
    cairis.misc.DocumentBuilder.build(self.db_proxy,docType,sectionFlags,typeFlags,fileName,docDir)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 2311, in build
    specDoc = buildPersonasBody(p,sectionFlags,docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 2262, in buildPersonasBody
    specDoc += tasks(p,docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 800, in tasks
    chapterTxt += modelSection(p,'Task',docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 1285, in modelSection
    if (buildModel(p,environmentName,modelType,modelFile,'',fileSuffix) == True):
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 194, in buildModel
    drawGraph(model.graph(),'dot',graphFile,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/KaosModel.py", line 288, in graph
    self.buildNode(element[0],element[1])
  File "/home/cairisuser/cairis/cairis/misc/KaosModel.py", line 103, in buildNode
    if (currentScore > highestScore):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
Build the book set list...
Build the listings...
XSLT stylesheets DocBook - LaTeX 2e (0.3.10)
===================================================
Build report.pdf
pdflatex failed
report.tex:7272: Something's wrong--perhaps a missing \item.
report.tex:7272: leading text: \end{itemize}
Unexpected error occured
Error: pdflatex compilation failed
ERROR:cairisd:[500] Unknown error: report file not found
ERROR:flask.app:Exception on /api/documentation/type/Data Protection Impact Assessment/format/PDF [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/DocumentationController.py", line 74, in get
    raise CairisHTTPError(status_code=500,message='report file not found',status='Unknown error')
cairis.daemon.CairisHTTPError.CairisHTTPError: 500 Internal Server Error: None
INFO:werkzeug:127.0.0.1 - - [27/Jul/2019 15:34:11] "GET /api/documentation/type/Data%20Protection%20Impact%20Assessment/format/PDF?session_id=hOdAmk0D0XSmQ9XNDhF1ukBzqF0Aeqm8&filename=report HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [27/Jul/2019 15:35:43] "GET /api/documentation/type/Requirements/format/PDF?session_id=hOdAmk0D0XSmQ9XNDhF1ukBzqF0Aeqm8&filename=report HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/DocumentationController.py", line 64, in get
    dao.generate_documentation(fileName,doc_type,sectionFlags,doc_format)
  File "/home/cairisuser/cairis/cairis/data/DocumentationDAO.py", line 35, in generate_documentation
    cairis.misc.DocumentBuilder.build(self.db_proxy,docType,sectionFlags,typeFlags,fileName,docDir)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 2309, in build
    specDoc = buildReqSpecBody(p,sectionFlags,docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 2167, in buildReqSpecBody
    specDoc += tasks(p,docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 800, in tasks
    chapterTxt += modelSection(p,'Task',docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 1285, in modelSection
    if (buildModel(p,environmentName,modelType,modelFile,'',fileSuffix) == True):
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 194, in buildModel
    drawGraph(model.graph(),'dot',graphFile,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/KaosModel.py", line 288, in graph
    self.buildNode(element[0],element[1])
  File "/home/cairisuser/cairis/cairis/misc/KaosModel.py", line 103, in buildNode
    if (currentScore > highestScore):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
INFO:werkzeug:127.0.0.1 - - [27/Jul/2019 15:36:14] "GET /api/documentation/type/Personas/format/PDF?session_id=hOdAmk0D0XSmQ9XNDhF1ukBzqF0Aeqm8&filename=report HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cairisuser/cairis/cairis/controllers/DocumentationController.py", line 64, in get
    dao.generate_documentation(fileName,doc_type,sectionFlags,doc_format)
  File "/home/cairisuser/cairis/cairis/data/DocumentationDAO.py", line 35, in generate_documentation
    cairis.misc.DocumentBuilder.build(self.db_proxy,docType,sectionFlags,typeFlags,fileName,docDir)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 2311, in build
    specDoc = buildPersonasBody(p,sectionFlags,docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 2262, in buildPersonasBody
    specDoc += tasks(p,docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 800, in tasks
    chapterTxt += modelSection(p,'Task',docDir,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 1285, in modelSection
    if (buildModel(p,environmentName,modelType,modelFile,'',fileSuffix) == True):
  File "/home/cairisuser/cairis/cairis/misc/DocumentBuilder.py", line 194, in buildModel
    drawGraph(model.graph(),'dot',graphFile,fileSuffix)
  File "/home/cairisuser/cairis/cairis/misc/KaosModel.py", line 288, in graph
    self.buildNode(element[0],element[1])
  File "/home/cairisuser/cairis/cairis/misc/KaosModel.py", line 103, in buildNode
    if (currentScore > highestScore):
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### Steps to reproduce the behaviour
I tried DPIA, Reqs, and Personas as word docs, then repeated for PDFs.

### Version of CAIRIS
Very latest

**Comment by failys** [comment]
pandoc is now an installation dependency. You need to re-run the apt-get install command here: https://cairis.readthedocs.io/en/latest/install.html#installation-and-configuration-via-github
